CREATE TABLE RESERVATION
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    identifier VARCHAR NOT NULL,
    reservation_owner_identifier VARCHAR NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    number_of_participants int NOT NULL,
    room_id int NOT NULL references room(id)
);